### ISSUE TITLE
entrypoint 和 cmd 解析有问题

### ISSUE THREAD

**Issue by stenote** [iamfat/docker-parse#4]
如下，Dockerfile 片段：

```
FROM debian:jessie

RUN (apt-get update &&\
  apt-get install -y curl wget jq)
### use docker-1.6.2; upgrading will break password decryption
RUN (wget "https://get.docker.com/builds/Linux/x86_64/docker-1.6.2" -O /usr/bin/docker &&\
  chmod +x /usr/bin/docker)
ADD migrator.sh /usr/local/bin/migrator.sh

ENTRYPOINT ["/usr/local/bin/migrator.sh"]
CMD [""]
```

摘抄自:  [这里](https://github.com/docker/migrator/blob/master/Dockerfile)

docker run 命令:

```
$ docker run -it \
    --entrypoint=/bin/bash \
    -v /home/may/migrator.sh:/target/migrator.sh \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e V1_REGISTRY=172.17.42.1:5000 \
    -e V2_REGISTRY=172.17.42.1:4999 \
    docker/migrator:latest
```

使用 docker-parse  进行检查后， 结果如下:

``` python
Traceback (most recent call last):
  File "/usr/local/bin/docker-parse", line 9, in <module>
    load_entry_point('docker-parse==0.1.9', 'console_scripts', 'docker-parse')()
  File "/usr/local/lib/python2.7/dist-packages/docker_parse/__init__.py", line 91, in main
    for v in conf['Cmd']:
TypeError: 'NoneType' object is not iterable
```

**Comment by iamfat** [comment]
fixed
